### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by khomaldi** [Kirill-Garbar/search-engine-infra#1]
Hello. Are you sure you want to keep it here? [click](https://github.com/Kirill-Garbar/search-engine-infra/blob/2d3cad7f235778031be97c01a042e8d35e3a45f7/ansible/k8s-charts/gitlab-omnibus/values.yaml#L2)

`postgresPassword: NDl1ZjNtenMxcWR6NXZnbw==
initialSharedRunnersRegistrationToken: "tQtCbx5UZy_ByS7FyzUH"
mattermostAppSecret: NDl1ZjNtenMxcWR6NXZnbw==
runnerRegistrationToken: "tQtCbx5UZy_ByS7FyzUH"
healthCheckToken: 'SXBAQichEJasbtDSygrD'`

**Comment by Kirill-Garbar** [comment]
Hello. It doesn't matter now :) Thank you.
How did you find my repo? :)

**Comment by khomaldi** [comment]
> How did you find my repo? :)

I used the search by "password" 😄

**Comment by Kirill-Garbar** [comment]
:) This is project for studying DevOps. These passwords/tokens are default for Helm Chart. These passwords are not mine.
